### ISSUE TITLE
Feat: Hint AllocFelt252Dict #36

### ISSUE THREAD

**Issue by jkktom** [NethermindEth/cairo-vm-go#120]
This issue is to implement the hint of AllocFelt252Dict to the project.

**Comment by jkktom** [comment]
#36 Hint AllocFelt252Dict

**Comment by jkktom** [comment]
Closed : Needs internal review required

**Comment by rodrigo-pino** [comment]
Reopening:
> This type of issues which introduce new features is better to leave them open until done. We can add a `block` label if we cannot solve it right away

**Comment by rodrigo-pino** [comment]
solved in #146
