### ISSUE TITLE
Add Hint Parsing to Starknet Contract Parsing

### ISSUE THREAD

**Issue by rodrigo-pino** [NethermindEth/cairo-vm-go#14]
We need to add hint parsing to our Parsing logic that deals with Starknet compiled contracs.

You should implement this [program.go](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/program/program.go) 

Also, files could be given a proper name in the process. A suggestion would be calling the folder `parsers` and the script `starknet_contract_parser.go`

**Comment by swapnilraj** [comment]
When you say hint parsing, do we need a full-blown Python parser?

**Comment by rodrigo-pino** [comment]
Nop, luckily the compiled contracts doesn't display the hint code but the hint name as well as the info it uses. An example would look like this:
```
"hints": [
    [
      0,
      [
        {
          "TestLessThanOrEqual": {
            "lhs": {
              "Immediate": "0x0"
            },
            "rhs": {
              "Deref": {
                "register": "FP",
                "offset": -6
              }
            },
            "dst": {
              "register": "AP",
              "offset": 0
            }
          }
        }
      ]
    ],
    [
      19,
      [
        {
          "AllocSegment": {
            "dst": {
              "register": "AP",
              "offset": 0
            }
          }
        }
      ]
    ],
....
```
Here we are showing at least two hints: "TestLessThanOrEqual" and "AllocSegment", the VM would identify them and call the corresponding Go code

**Comment by rodrigo-pino** [comment]
You can look at an output yourself by following this flow: 
1. compile starknet-contract to sierra
2. compile sierra output to casm
3. read the output

It must be a contract, normal cairo files have different output

**Comment by greged93** [comment]
Is this available? Would love to work on it

**Comment by greged93** [comment]
@rodrigo-pino I have a question concerning the compiled example you provided: this was compiled from a Starknet contract, hence also using the Starknet compiler. The output serialized output is quite different from a pure cairo compiled file. 

Since you are building a cairo vm, we should probably compile any example we build using the cairo-compiler at [cairo-lang](https://github.com/starkware-libs/cairo-lang/tree/master). Here is an example of the hint field compiled with the python compiler:
```
"hints": {
        "3": [
            {
                "accessible_scopes": [
                    "starkware.cairo.common.memcpy",
                    "starkware.cairo.common.memcpy.memcpy"
                ],
                "code": "vm_enter_scope({'n': ids.len})",
                "flow_tracking_data": {
                    "ap_tracking": {
                        "group": 0,
                        "offset": 0
                    },
                    "reference_ids": {
                        "starkware.cairo.common.memcpy.memcpy.dst": 0,
                        "starkware.cairo.common.memcpy.memcpy.len": 2,
                        "starkware.cairo.common.memcpy.memcpy.src": 1
                    }
                }
            }
        ],
        "11": [
            {
                "accessible_scopes": [
                    "starkware.cairo.common.memcpy",
                    "starkware.cairo.common.memcpy.memcpy"
                ],
                "code": "n -= 1\nids.continue_copying = 1 if n > 0 else 0",
                "flow_tracking_data": {
                    "ap_tracking": {
                        "group": 0,
                        "offset": 5
                    },
                    "reference_ids": {
                        "starkware.cairo.common.memcpy.memcpy.__temp0": 5,
                        "starkware.cairo.common.memcpy.memcpy.continue_copying": 6,
                        "starkware.cairo.common.memcpy.memcpy.dst": 0,
                        "starkware.cairo.common.memcpy.memcpy.frame": 4,
                        "starkware.cairo.common.memcpy.memcpy.len": 2,
                        "starkware.cairo.common.memcpy.memcpy.next_frame": 7,
                        "starkware.cairo.common.memcpy.memcpy.src": 1
                    }
                }
            }
        ],
```
Let me know if you agree.

**Comment by rodrigo-pino** [comment]
The compiler from [cairo-lang](https://github.com/starkware-libs/cairo-lang/tree/master) is no longer being supported. We aim to have parsers for the current compiler written in rust. 

There are three compilers for Cairo:
1. Normal Cairo file compiler in Rust
2. Starknet Contract Compiler in Rust
3. Compiler in python (i.e. the one in cairo-lang)

This PR is going to complete the parsing for the second type of compiler which produces this type of output.
We would like after that support Cairo compiler for simple Cairo files (1)

Regarding the third compiler, the one from cairo-lang. Nobody is using it right now, since it requires to write Cairo Zero code. Lambdaass target this compiler on their VM but remember they started working on this before (1) and (2) where even finished so it made sense. Right now it does not makes sense to me to target an old compiler with deprecated output.

**Comment by rodrigo-pino** [comment]
Also, if you take a peek at the code of the [runner](https://github.com/starkware-libs/cairo/tree/main/crates/cairo-lang-runner) from the rust Cairo repo you will notice how they define their own runner, using the VM for Cairo 1. Practically dismissing the parts of the rust vm that uses Cairo Zero.

**Comment by rodrigo-pino** [comment]
Having a parser for Cairo Zero would be very beneficial though. It would allow us to easily compare to LC vms which uses the Cairo Zero code.

**Comment by greged93** [comment]
I see, that clears everything up, will keep working on parsing the hints from the rust starknet compiler !
