### ISSUE TITLE
Run separate cairo integration test files as a separate Go test

### ISSUE THREAD

**Issue by quasilyte** [NethermindEth/cairo-vm-go#201]
Doing that would allow us to run a specific file test to skip through the ones that are not relevant to the local changes.

**Comment by rodrigo-pino** [comment]
In ../integration_tests/cairozero_test.go there is a `filter` variable in the `TestCairoZeroFile` function that is empty by default. We want it so it can be set by a global env var (e.g. `INTEGRATION_FILTER`) and if not, it stays as an empty string.

**Comment by wugalde19** [comment]
Hi @rodrigo-pino @quasilyte 
I'm basically done with my other issue assigned
Can I work on this one once the other one is merged?

**Comment by xiaolou86** [comment]
Hello @quasilyte @rodrigo-pino I would like to contribuite on this if it's not yet assigned to anyone. 

I think it's a good first issue for me.

Thank you very much.

**Comment by cicr99** [comment]
Hey @xiaolou86 are you still interested on working on this issue? It's yours if you want it

**Comment by xiaolou86** [comment]
Sure. Thank you very much @cicr99

**Comment by MaksymMalicki** [comment]
Right now the functionality works as expected, so thats great 🚀. I'm wondering if it wouldn't be better to allow multiple files to be provided in the .env variable and separated by comma. Sometimes it's useful to test multiple functionalities at once

**Comment by xiaolou86** [comment]
Good idea. I have made this improvement.
