### ISSUE TITLE
DecodeMemory used in tests can panic on some inputs

### ISSUE THREAD

**Issue by quasilyte** [NethermindEth/cairo-vm-go#204]
Right now it seems like the memory trace doesn't always have the highest memory address (index) in its last memory trace element.
This is an assumption we make when decoding the memory:
```
lasMemIndex := binary.LittleEndian.Uint64(content[lastContentInd : lastContentInd+addrSize])
```
This seems to be working with `layout=plain`, but it fails to decode the `layout=small` memory trace.

(Or maybe we're reading whole 8 bytes that can contain some bits for the "segment". Since the segment is always 0 in the simplest cases, it could work correctly. But I don't know the exact memory encoding yet.)

Here is an example:
```
addr=80
addr=81
addr=82
addr=1635
addr=1634
addr=1637
addr=1636
addr=83
addr=84
```
I would assume that values like 1635 come from a range_check builtin segment (my test uses it).

**Comment by quasilyte** [comment]
There are 2 ways for the address to be encoded:
```
    def to_bytes(value: "MaybeRelocatable", n_bytes: int, byte_order: Endianness) -> bytes:                                             
        """                                                                                                                             
        Serializes RelocatableValue as:                                                                                                 
        1bit |   SEGMENT_BITS |   OFFSET_BITS                                                                                           
        1    |     segment    |   offset                                                                                                
        Serializes int as                                                                                                               
        1bit | num                                                                                                                      
        0    | num                                                                                                                      
        """
```
But for the use cases I care about right now this is not an issue, because all values are encoded using the second schema.

**Comment by quasilyte** [comment]
In this particular case, it all happens due to the different segment relocation between the two runners.
Here is the cairo-run segments relocation table for this test:
```
Segment relocation table:
0     1
1     68
2     98
3     98
4     1634
5     2146
```
1634 is a range_check builtin.

**Comment by har777** [comment]
Fixed in https://github.com/NethermindEth/cairo-vm-go/pull/397
