### ISSUE TITLE
Documentation Page Not Found

### ISSUE THREAD

**Issue by MrExcel2019** [NethermindEth/cairo-vm-go#205]
Here, Nethermind documentation **page not found** https://docs.nethermind.io/nethermind/

**Reference:** ![screenshot-docs nethermind io-2024 02 14-22_17_30](https://github.com/NethermindEth/cairo-vm-go/assets/56793406/b3a8c09b-f053-4363-80df-bf58aa9d26ca)

**Comment by cicr99** [comment]
Hi @MrExcel2019 the documentation for the nethermind client can be found at https://docs.nethermind.io/
If you are having trouble with a specific page you should probably open an issue in the repo of that project https://github.com/NethermindEth/nethermind

If what you are looking for instead is the documentation for the cairo-vm-go I invite you to checkout the [Documentation Section](https://github.com/NethermindEth/cairo-vm-go#documentation) in our Readme

**Comment by MrExcel2019** [comment]
Thank you @cicr99
