### ISSUE TITLE
Add a Parser for Compiled Cairo Zero File

### ISSUE THREAD

**Issue by rodrigo-pino** [NethermindEth/cairo-vm-go#23]
We are adding a Json Unmarshaller for compiled Cairo Zero Files. Cairo Zero allow us to write programs directly in CASM, allowing for greater control when testing specific instructions

Useful docs:
* The Cairo Lang Compiler: https://github.com/starkware-libs/cairo-lang
* The Cairo Zero Docs: https://docs.cairo-lang.org/0.12.0/hello_cairo/index.html

**Comment by krafugo** [comment]
I'll do it

**Comment by rodrigo-pino** [comment]
Solved on #40
