### ISSUE TITLE
UsortVerifyMultiplicityBody

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#235]
Processes each position of a specific value in the sorted output, updating indices for verification.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/usort.cairo#L92

Depends on issue #245

**Comment by wugalde19** [comment]
@cicr99 
Hi Carmen
Hope you are doing great.
Looking forward to contributing and learning more about the project

If not yet assigned, can I get the chance to work on this issue?

**Comment by cicr99** [comment]
Hey @wugalde19 sure! Make sure to check out this [guide](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/hintrunner/zero/README.md) on how to add new hints first. Let us know if you have any questions

**Comment by wugalde19** [comment]
> Hey @wugalde19 sure! Make sure to check out this [guide](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/hintrunner/zero/README.md) on how to add new hints first. Let us know if you have any questions

Hi @cicr99 
Sure I'll take a look and I'll reach out as soon as I've gone through that doc and have set up the project
Thanks for the opportunity
