### ISSUE TITLE
Pow

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#238]
Calculates the least significant bit of the exponent of a number within a prime field.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/pow.cairo#L28C8-L28C54

**Comment by quasilyte** [comment]
This hint requires a new ids manager method: insert due to the local variable re-assignment inside a hint code.

**Comment by quasilyte** [comment]
Here is a simplified example:
```
%builtins output

from starkware.cairo.common.serialize import serialize_word

func main{output_ptr: felt*}() {
    alloc_locals;

    [ap] = 5, ap++;  // i
    [ap] = 10, ap++; // initial x value

loop:
    [ap] = [ap-2] - 1, ap++; // i -= 1
    let prev_x = [ap-2];
    let x = [ap];
    %{ ids.x = ids.prev_x + 1 %}
    ap += 1;
    jmp loop if [ap-2] != 0;

    local x0 = [ap-9];
    local x1 = [ap-7];
    local x2 = [ap-5];
    local x3 = [ap-3];
    local x4 = [ap-1];
    serialize_word(x0);
    serialize_word(x1);
    serialize_word(x2);
    serialize_word(x3);
    serialize_word(x4);

    return ();
}
```
Every time the hint is executed, `ids.x` should write to a new memory segment.

The lambdaclass Go VM uses Insert API of the IDs manager for that.
