### ISSUE TITLE
Sqrt

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#240]
Calculates the square root of a given value, ensuring it falls within a specific range.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/math.cairo#L423

It will probably be useful to have a look into `hintrunner/core/FieldSqrt`.

**Comment by Tomi-3-0** [comment]
Hello @cicr99; I would like to start working on this

**Comment by cicr99** [comment]
Perfect @Tomi-3-0, just assigned you to the task. Please review this [guide](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/hintrunner/zero/README.md) on how to implement new Cairo 0 hints

**Comment by Tomi-3-0** [comment]
Hello @cicr99. I submitted a [PR](https://github.com/NethermindEth/cairo-vm-go/pull/313) for this [issue](https://github.com/NethermindEth/cairo-vm-go/issues/240). Please review

**Comment by Tomi-3-0** [comment]
Hi @cicr99. I opened a fresh [PR](https://github.com/NethermindEth/cairo-vm-go/pull/316) for this issue with the requested changes. Please review

**Comment by cicr99** [comment]
Perfect. Great work! Pr approved and merged!
