### ISSUE TITLE
SignedDivRem

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#242]
Performs a signed division and modulus operation on a given value, ensuring the quotient is within a specified range.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/math.cairo#L329

> Note: This hint uses `divmod` function and `range_check_builtin`, both have been already implemented in this hint section so just check the code for clarification

**Comment by Tomi-3-0** [comment]
Hello @cicr99 , I would like to work on this if it isn't assigned yet
