### ISSUE TITLE
IsQuadResidue

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#243]
Determines if a given number is a quadratic residue and calculates its square root accordingly.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/math.cairo#L455

The main problem here is to implement `is_quad_residue` function from the `starkware.python` package. Maybe `Legendre()` function from the `Element` library used in the project will help with that

**Comment by Tomi-3-0** [comment]
Hi @cicr99 , I will like to work on this

**Comment by Tomi-3-0** [comment]
Hello @cicr99, I opened a [PR](https://github.com/NethermindEth/cairo-vm-go/pull/322) in regards to this issue.
Please review. Thank you!

**Comment by cicr99** [comment]
Addressed in Pr #322
