### ISSUE TITLE
MemcpyEnterScope

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#250]
Enters a new scope for the memory copy operation with a specified length.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/memcpy.cairo#L12

Depends on #245

**Comment by Alvarodb** [comment]
Hey @cicr99, I want to help with this if it's ok!

**Comment by rodrigo-pino** [comment]
Hey @Alvarodb sure, it's yours

**Comment by Alvarodb** [comment]
Hello @rodrigo-pino @cicr99,

After checking hintcode.go and identifying the vmEnterScopeCode hint definition "vm_enter_scope()", I followed its usage to GetHintFromCode in zerohint.go, and then to hint_memcpy.go in the function createVMEnterScopeHinter. This function is responsible for creating the scope, and I think it aligns with the request and  the related PR.

Here is the code I propose:

```go
func createVMEnterScopeHinter(resolver hintReferenceResolver) (hinter.Hinter, error) {
    return &GenericZeroHinter{
        Name: "VMEnterScope",
        Op: func(vm *VM.VirtualMachine, ctx *hinter.HintRunnerContext) error {
			n, err := ctx.ScopeManager.GetVariableValue("n")
			if err != nil {
				return err
			}
         	ctx.ScopeManager.EnterScope(map[string]any{"n": n});
            return nil
        },
    }, nil
}
```

My unit tests are passing okay, and I believe the scope_test.go should adequately cover this functionality. Please let me know if there's anything else I should test or if I'm missing something. This is my first contribution to StarkNet related projects. Thanks!

**Comment by cicr99** [comment]
Hi @Alvarodb

Some comments regarding your solution. Notice in the code of the hint:
```
%{ vm_enter_scope({'n': ids.len}) %}
```

You are using `ids.len`, so you need to pass `len` variable as an argument for your hint constructor. You are creating a new scope and defining variable "n" and its value there, so no need to check if a variable "n" existed in the current scope, you can just use the value of the `len` variable to create the `scopeMap` you are passing to `EnterScope`. Also notice in the python code that passing an empty map is not an option here.

Does this make sense?

**Comment by Alvarodb** [comment]
@cicr99 

Thank you for your feedback—it makes the requirements a bit clearer.

However, I have a couple of clarifications to request:

Python Code Reference: You mentioned to "also notice in the Python code..."—could you specify which Python code or section you are referring to? I want to ensure I understand all parts of the integration correctly.

Parameter Handling in createVMEnterScopeHinter: Regarding the addition of the len variable, should this be explicitly passed as a new parameter to the createVMEnterScopeHinter function, or is it intended to be part of the resolver parameter from which I should extract it? Understanding this will help me implement it correctly in the hinter constructor.

Thanks again!

**Comment by cicr99** [comment]
@Alvarodb 

Python Code Reference: This is the reference link in the description of this issue. It points to the code of the hint, which is written in Python

Parameter Handling: If you check the compiled output of file that's using the hint, you'll see the variables involved in the hint include `len`. When inside a hint you get `ids.<variable_name>` this is the hint is accessing a variable that was defined in the cairo code outside of the hint, so these are usually passed as parameters for the hint. This variable is saved in the resolver when we do the parsing of the cairo output, so for you to be able to access it you have to access the resolver with the name of the variable you want. If you check other hints already implemented you'll see we have two methods: 
- `createVMEnterScopeHinter` which is in charge of getting the variables from the resolver and call the hint constructor method `newVMEnterScopeHint` with all the parameters it needs.
- `newVMEnterScopeHint` which has the actual implementation of the hint

Let me know if it is clearer now

**Comment by Alvarodb** [comment]
Thanks, that explanation made things a lot clearer. Based on this, here is the code again. 

```go
func createVMEnterScopeHinter(resolver hintReferenceResolver) (hinter.Hinter, error) {
    return &GenericZeroHinter{
        Name: "VMEnterScope",
        Op: func(vm *VM.VirtualMachine, ctx *hinter.HintRunnerContext) error {
			len, err := resolver.GetResOperander("len")
			if err != nil {
				return err
			}
            ctx.ScopeManager.EnterScope(map[string]any{"n": len})
            return nil
        },
    }, nil
}
```

Let me know if there are any issues.

**Comment by MaksymMalicki** [comment]
Hi @Alvarodb! This generally looks great, however there are some styling things to deal with. 

- We create separate methods for fetching the ResOperanders, which has the name convetion of: create{HintName}Hinter
- Once the ResOperanders are fetched, they are passed as parameters to new method with name convention of: new{HintName}Hint (this is easier for testing)
- Try to add a comment with the hint code, where each line is followed by //> comment
- I think the hint name should be createMemcpyEnterScope
I think you are far enough to create a draft PR. Make sure to do that, so our conversation is smooth haha 😃

**Comment by Alvarodb** [comment]
Hey @MaksymMalicki, I've created the draft PR for your review. I believe I've addressed all the feedback you provided. Please let me know if there are any issues. Thanks a lot!
