### ISSUE TITLE
MemcpyContinueCopying

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#251]
Continues copying memory elements, decrementing the remaining length and setting a flag to continue if more elements are to be copied.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/memcpy.cairo#L24

Depends on #245

**Comment by danielcdz** [comment]
Hey @cicr99, I want to help with this if it's ok!

**Comment by cicr99** [comment]
Hey @danielcdz sure! I just assigned you to it. Let us know if you have any questions

**Comment by danielcdz** [comment]
Hey @cicr99 ! this is my first time contributing to OSS, for this issue, I was researching and I think that it is ok to follow the instructions of this [readme](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/hintrunner/zero/README.md#implementing-new-cairo-0-hints), and follow as an example this [pr](https://github.com/NethermindEth/cairo-vm-go/pull/32), what do you think? and is there another way to communicate and have more context about the project, maybe a Telegram group or chat?

**Comment by danielcdz** [comment]
Hello! @cicr99 I opened a draft pr, I'm not sure if I'm solving the issue as we want, here is the [pr](https://github.com/NethermindEth/cairo-vm-go/pull/359), it would be great if someone can help me a bit!

**Comment by MaksymMalicki** [comment]
Hey @danielcdz sorry for such long answer. I have left some comments on the PR. Overall it looks really good and this is the right direction. If you will still be working on it, try to add some tests as well
