### ISSUE TITLE
FastEcAddAssignNewY

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#270]
Calculates a new y-coordinate for fast elliptic curve addition.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/cairo_secp/ec.cairo#L222

**Comment by MaksymMalicki** [comment]
While checking the code of lambdalabs vm implementation, I see that this hint probably also utilizes execution context:
https://github.com/lambdaclass/cairo-vm_in_go/blob/31c3628bc10ebc1628685b3cdfa72d0e938b533e/pkg/hints/ec_hint.go#L370
