### ISSUE TITLE
BlockPermutation

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#282]
Applies the KECCAK block permutation function to a segment of memory.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/cairo_keccak/keccak.cairo#L293

**Comment by TAdev0** [comment]
@rodrigo-pino  may i be assigned?
