### ISSUE TITLE
KeccakWriteArgs

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#285]
Writes arguments for the KECCAK function, splitting 64-bit integers into low and high parts.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/keccak_utils/keccak_utils.cairo#L26

**Comment by TAdev0** [comment]
Hi @cicr99  is this issue available? if yes, may i be assigned? thanks!

**Comment by rodrigo-pino** [comment]
Here you have
