### ISSUE TITLE
SquashDictInnerAssertLenKeys

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#302]
Asserts the length of the keys array during the squashing process.

Reference: https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/squash_dict.cairo#L216

depends on #245

**Comment by jbmkahdeksan** [comment]
is this available? 
I'm interested :)

**Comment by jbmkahdeksan** [comment]
thanks!
