### ISSUE TITLE
Improve unit testing by allowing different types of operanders

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#332]
Currenty the testing structure we have creates `Deref` structs for the operanders we pass. This is consistent with ResOperanders, but if you would need a CellRef to be passed to the constructor it wouldn't be possible. It would be good to modify it as to allow us to pass the operander we need

**Comment by ebukizy1** [comment]
can i be assign this.. will love to work on it.

**Comment by TAdev0** [comment]
hi @ebukizy1  sorry for the late answer. This issue was not opened to external contributors. thanks for your interest though

**Comment by TAdev0** [comment]
@cicr99  still thinking about the best way to achieve this

**Comment by TAdev0** [comment]
Do you finally really need this? We finished unit tests for Cairo zero hints , would it really be an improvement ?

**Comment by cicr99** [comment]
Hey @TAdev0 you are right. This issue is deprecated now
