### ISSUE TITLE
Initialize scopes when creating hint context

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#345]
Currently the unit testing suit creates the context to pass down to the hint execution without initializing any of its members. The idea for this is to only initialize them when necessary. However, most of the hints use the ScopeManager, and there should always be at least the main scope. Hence, let's modify the code so when the context is created, the Scope Manager is also initialized

**Comment by fishonamos** [comment]
Hi @cicr99. Can this be assigned to me? I can solve of these issues.

**Comment by cicr99** [comment]
@fishonamos surely. I've just assigned you!
