### ISSUE TITLE
Resolve as BigInt3 structure

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#346]
Currently we use the following logic for resolving BigInt3 structures:
```
valMemoryValues, err := hinter.GetConsecutiveValues(vm, valAddr, int16(3))
if err != nil {
    return err
}

// [d0, d1, d2]
var valValues [3]*fp.Element

for i := 0; i < 3; i++ {
    valValue, err := valMemoryValues[i].FieldElement()
    if err != nil {
    	return err
    }
    valValues[i] = valValue
}
```
`valValues` is the argument that should be passed down to the `pack` functionality.

As this logic is repeated in the code several times, it would be beneficial to separate it in its own functionality, something like `ResolveAsBigInt3` passing the starting address of the structure in memory

**Comment by MoigeMatino** [comment]
Would like to take this on if that's okay.

**Comment by MoigeMatino** [comment]
@cicr99 Is there a specific file where this function should be stored?

**Comment by cicr99** [comment]
Hey @MoigeMatino sure! I just assigned you to it. This functionality should go into the `hintrunner/utils` folder as it's used by several hints. I would say to add it secp_utils.go file. Wdyt @har777 , since you've been working on that?

**Comment by har777** [comment]
Yeah thats the right file imo.

**Comment by MoigeMatino** [comment]
Here's the draft PR: #354
