### ISSUE TITLE
Add Core Hints to the VM

### ISSUE THREAD

**Issue by rodrigo-pino** [NethermindEth/cairo-vm-go#36]
We need to define all possible Hints applicable a program execution. The following is a list extracted from the [Rust CASM compiler](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-casm/src/hints/mod.rs) which defines all Core hints. Hints will be implemented in [pkg/hintrunner/hint.go](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/hintrunner/hint.go). `AllocSegment` and `TestLessThan` are already implemented as use examples. Tools that allow abstractions from the VM have been implemented as well, so minimal understanding of the VM is required. Of course if the hint directly affects the VM this may not apply.

The workflow is as follows: a contributor asks to get assigned one of the not-implemented hints and a dedicated issue is created. Once the issue is solved, the hint is marked accordingly.

### Core Hints

- [x] **AllocSegment** #31
  - Params: `dst: CellRef`
- [x] **TestLessThanOrEqual** #102 
  - Params: `lhs: ResOperand, rhs: ResOperand, dst: CellRef`
- [x] **TestLessThan** #31 
  - Params: `lhs: ResOperand, rhs: ResOperand, dst: CellRef`
- [x] **WideMul128** #37 
  - Params: `lhs: ResOperand, rhs: ResOperand, high: CellRef, low: CellRef`
  - Description: Multiplies two 128-bit integers and returns two 128-bit integers: the high and low parts of the product.
- [x] **DivMod** #41
  - Params: `lhs: ResOperand, rhs: ResOperand, quotient: CellRef, remainder: CellRef`
  - Description: Computes lhs/rhs and returns the quotient and remainder. Note: the hint may be used to write an already assigned memory cell.
- [x] **Uint256DivMod** #46 
  - Params: `dividend0: ResOperand, dividend1: ResOperand, divisor0: ResOperand, divisor1: ResOperand, quotient0: CellRef, quotient1: CellRef, remainder0: CellRef, remainder1: CellRef`
  - Description: Divides dividend (represented by 2 128bit limbs) by divisor (represented by 2 128bit limbs). Returns the quotient (represented by 2 128bit limbs) and remainder (represented by 2 128bit limbs). In all cases - `name`0 is the least significant limb.
- [x] **Uint512DivModByUint256** #112 
  - Params: `dividend0: ResOperand, dividend1: ResOperand, dividend2: ResOperand, dividend3: ResOperand, divisor0: ResOperand, divisor1: ResOperand, quotient0: CellRef, quotient1: CellRef, quotient2: CellRef, quotient3: CellRef, remainder0: CellRef, remainder1: CellRef`
  - Description: Divides dividend (represented by 4 128bit limbs) by divisor (represented by 2 128bit limbs). Returns the quotient (represented by 4 128bit limbs) and remainder (represented by 2 128bit limbs). In all cases - `name`0 is the least significant limb.
- [x] **SquareRoot** #110 
  - Params: `value: ResOperand, dst: CellRef`
- [x] **Uint256SquareRoot** #131 
  - Params: `value_low: ResOperand, value_high: ResOperand, sqrt0: CellRef, sqrt1: CellRef, remainder_low: CellRef, remainder_high: CellRef, sqrt_mul_2_minus_remainder_ge_u128: CellRef`
  - Description: Computes the square root of value_high<<128+value_low, stores the 64bit limbs of the result in sqrt0 and sqrt1 as well as the 128bit limbs of the remainder in remainder_low and remainder_high. The remainder is defined as `value - sqrt**2`. Lastly it checks whether `2*sqrt - remainder >= 2**128`.
- [x] **LinearSplit** #111 
  - Params: `value: ResOperand, scalar: ResOperand, max_x: ResOperand, x: CellRef, y: CellRef`
  - Description: Finds some `x` and `y` such that `x * scalar + y = value` and `x <= max_x`.
- [x] **AllocFelt252Dict**  #146 
  - Params: `segment_arena_ptr: ResOperand`
- [x] **Felt252DictEntryInit** #146 
  - Params: `dict_ptr: ResOperand, key: ResOperand`
- [x] **Felt252DictEntryUpdate** #146 
  - Params: `dict_ptr: ResOperand, value: ResOperand`
- [x] **GetSegmentArenaIndex** #146 
  - Params: `dict_end_ptr: ResOperand, dict_index: CellRef`
- [x] **InitSquashData** #146 
  - Params: `dict_accesses: ResOperand, ptr_diff: ResOperand, n_accesses: ResOperand, big_keys: CellRef, first_key: CellRef`
- [x] **GetCurrentAccessIndex** #146 
  - Params: `range_check_ptr: ResOperand`
- [x] **ShouldSkipSquashLoop** #146 
  - Params: `should_skip_loop: CellRef`
- [x] **GetCurrentAccessDelta** #146 
  - Params: `index_delta_minus1: CellRef`
- [x] **ShouldContinueSquashLoop** #146 
  - Params: `should_continue: CellRef`
- [x] **GetNextDictKey** #146 
  - Params: `next_key: CellRef`
- [x] **AssertLeFindSmallArcs** #155 
  - Params: `range_check_ptr: ResOperand, a: ResOperand, b: ResOperand`
- [x] **AssertLeIsFirstArcExcluded** #165 
  - Params: `skip_exclude_a_flag: CellRef`
- [x] **AssertLeIsSecondArcExcluded** #166 
  - Params: `skip_exclude_b_minus_a: CellRef`
- [x] **RandomEcPoint** #173 
  - Params: `x: CellRef, y: CellRef`
- [x] **FieldSqrt** #178 
  - Params: `val: ResOperand, sqrt: CellRef`
  - Description: Computes the square root of `val`, if `val` is a quadratic residue, and of `3 * val` otherwise. Since 3 is not a quadratic residue, exactly one of `val` and `3 * val` is a quadratic residue (unless `val` is 0). This allows proving that `val` is not a quadratic residue.
- [x] **DebugPrint**
  - Params: `start: ResOperand, end: ResOperand`
- [x] **AllocConstantSize** #105 
  - Params: `size: ResOperand, dst: CellRef`
- [x] **TestLessThanOrEqualAddress** #628 
  - Params: `lhs: ResOperand, rhs: ResOperand, dst: CellRef`
  - Description: Variant of TestLessThanOrEqual that compares addresses.
- [x] **U256InvModN** #630 
  - Params: `b0: ResOperand, b1: ResOperand, n0: ResOperand, n1: ResOperand, g0_or_no_inv: CellRef, g1_option: CellRef, s_or_r0: CellRef, s_or_r1: CellRef, t_or_k0: CellRef, t_or_k1: CellRef`
  - Description: Provides the inverse of b (represented by 2 128-bit limbs) modulo n (represented by 2 128-bit limbs), or a proof that b has no inverse. Check [here](https://github.com/starkware-libs/cairo/blob/54804c8730dabea31a2b80034fe2c3911e79adf5/crates/cairo-lang-casm/src/hints/mod.rs#L255) for more information
- [ ] **EvalCircuit** #669 
  - Params: `n_add_mods: ResOperand, add_mod_builtin: ResOperand, n_mul_mods: ResOperand, mul_mod_builtin: ResOperand`

**Comment by greged93** [comment]
Hey @rodrigo-pino would love to start by an easy one like `WideMul128`

**Comment by coburn24** [comment]
Hey @rodrigo-pino can i try Uint256DivMod

**Comment by rodrigo-pino** [comment]
@coburn24 sure! Please comment on issue #46 so I can properly assign you!

**Comment by jkktom** [comment]
@rodrigo-pino 
May I try below hints.
-TestLessThanOrEqual
-WideMul128

**Comment by greged93** [comment]
hey @rodrigo-pino, I'm down to take `Uint512DivModByUint256` if it's free

**Comment by coxmars** [comment]
> Just added three more core hints to be implemented

Hi @cicr99 how are you? I would like to help with "U256InvModN" if it's free 🫡
