### ISSUE TITLE
Felt values in hints representing array length

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#383]
There are cases such as this [hint](https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/memcpy.cairo#L24):
```
%{
        n -= 1
        ids.continue_copying = 1 if n > 0 else 0
%}
```
where the value of n is supposed to be a felt, as you can see in its definition [here](https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/memcpy.cairo#L12):
```
%{ vm_enter_scope({'n': ids.len}) %}
```
where `len` is of type felt.

However, in practice, the actual value of `n` cannot be a value of 252 bits since that wouldn't be feasible to compute, as this is representing the length of an array. `n` should fit in int64. If we do the conversion from the moment we define the variable then all operations regarding `n` would be a lot easier and more efficient, as the way we can handle felts is using Element from [this library](https://github.com/Consensys/gnark-crypto/tree/master/ecc/stark-curve/fp).

**Task**: Look for all the places in the code of hints where this can be optimized and do so. Notice you'll also need to modify all the code related to operations with these variables

**Comment by fishonamos** [comment]
I will love to work on this @cicr99

**Comment by Osatuyi** [comment]
Hi @cicr99 . Can I be asssigned this please

**Comment by cicr99** [comment]
Hi @Osatuyi, thanks for your interest in contributing. I'm not sure if @fishonamos is currently working on this or is still interested in working on it. Let him answer first and then we can assign someone to the issue. Sorry for the inconvenience

**Comment by Osatuyi** [comment]
allright. No problem.

**Comment by fishonamos** [comment]
Hi @cicr99 . Should I raise a PR for this?

**Comment by cicr99** [comment]
Hi @fishonamos yes! When you have it done pls raise a PR.
Any updates?

**Comment by fishonamos** [comment]
@cicr99. How can i reach out to you?

**Comment by TAdev0** [comment]
@fishonamos  any updates? do you need any help? dont hesitate to push a draft PR

**Comment by TAdev0** [comment]
@fishonamos  you asked to work on it almost 2 months ago, will assign you i'm working on it right now
