### ISSUE TITLE
Move GetConsecutiveValues functionality to memory package

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#384]
Currently `GetConsecutiveValues` functionality (and similar ones) are implemented in the `hintrunner/hinter/operand.go` file. The ideal place for them to be is the memory package.
Moving these functionalities there implies doing modifications to several files, as lots of hints use them.

Leaving them where they are is currently a problem. See PR #354

**Comment by murluki** [comment]
can you assign me, please?

**Comment by TAdev0** [comment]
Hi @murluki , 
Actually someone is already working on it

**Comment by MoigeMatino** [comment]
Currently working on this cc @cicr99

**Comment by TAdev0** [comment]
@MoigeMatino  feel free to reach out if you have any issue

**Comment by MoigeMatino** [comment]
> @MoigeMatino feel free to reach out if you have any issue

Thanks @TAdev0 . Just created a PR, getting some errors when running `make unit`, not sure how to solve those. I'd appreciate your help with those, thanks!
