### ISSUE TITLE
 README.md needs to be updated after `GetConsecutiveValues` has been moved to memory package and renamed `GetConsecutiveMemoryValues`

### ISSUE THREAD

**Issue by MoigeMatino** [NethermindEth/cairo-vm-go#419]
Update the README.md to reflect the new definition of GetConsecutiveMemoryValues from GetConsecutiveValues as shown here in the current documentation:

> The operanders allow you to get the address in memory of the variable you need to use. When this variable is a felt just reading the value from that address is enough, but sometimes the variable is actually a struct so you need to get several consecutive values in memory, for that you can use `GetConsecutiveValues(vm *VM.VirtualMachine, ref ResOperander, size int16)` method. For example in `uint256add` hint you need to add `a` and `b` which are both `Uint256` structs, so we used `GetUint256AsFelts` utility which basically calls that function with size 2.

**Comment by MoigeMatino** [comment]
Hi @cicr99 May i work on this issue following the changes I made the changes to the GetConsecutiveValues function reflected on PR #396 ?

**Comment by TAdev0** [comment]
@MoigeMatino  sure you can update the readme !
