### ISSUE TITLE
Move `WriteToNthStructField` function to Memory package

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#426]
`WriteToNthStructField` function is currently defined in Hinter package in _operand.go_ file. This is not the right place for this function, which writes some value to memory. Nothing related to operands.
 
 1. Move the function to the Memory package in the appropriate file
 2. Update the codebase where it is needed

**Comment by princeibs** [comment]
Can I hop on this?

**Comment by charans29** [comment]
Hello, @TAdev0 shall I work on this, if it's still open for assignment.

**Comment by EmmanuelAR** [comment]
Hello team @TAdev0 
I already covert this function because i have to move WriteToNthStructField too, because inside in the WriteUint256ToAddress i have to call WriteToNthStructField 

Heres the PR  #428

**Comment by TAdev0** [comment]
#428
