### ISSUE TITLE
Move `WriteUint256ToAddress` function to Memory package

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#427]
`WriteUint256ToAddress` function is currently defined in Hinter package in operand.go file. This is not the right place for this function, which writes some uint256 value to a specified memory address. Nothing related to operands.

1. Move the function to the Memory package in the appropriate file
2. Update the codebase where it is needed

**Comment by EmmanuelAR** [comment]
Heeey @TAdev0 can i work on this?

**Comment by EmmanuelAR** [comment]
Hey @TAdev0, thanks for the opportunity! 

Do you have Telegram so I can contact you if I have a question?

Here's mine: https://t.me/EmmanuelDevCr

**Comment by TAdev0** [comment]
please write any questions here so that everyone can follow what's going on with this issue

**Comment by EmmanuelAR** [comment]
excellent, working now...

**Comment by EmmanuelAR** [comment]
Also i fix this link in the readme file  @TAdev0, you can see the change in the last commit of the pr #428 

![Screenshot 2024-05-23 232742](https://github.com/NethermindEth/cairo-vm-go/assets/54730752/bdd45709-bdb5-4cf8-bd50-73a1fbfe15af)

Pass link
![image](https://github.com/NethermindEth/cairo-vm-go/assets/54730752/57d3da20-6ef0-4de2-be58-eb2843118a0e)

NEW LINK
![image](https://github.com/NethermindEth/cairo-vm-go/assets/54730752/35e999db-69af-4039-97e3-e2ecfe4f9e63)

**Comment by TAdev0** [comment]
#428
