### ISSUE TITLE
`MemcpyContinueCopying` hint is wrongly implemented

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#436]
the hint is 

```
	//> n -= 1
        //> ids.continue_copying = 1 if n > 0 else 0
```

`n` is a value stored in the scope.

Currently we do

```
		newN := new(f.Element)
			newN = newN.Sub(n.(*f.Element), &utils.FeltOne)

			if err := ctx.ScopeManager.AssignVariable("n", newN); err != nil {
				return err
			}
```

this is not the expected behavior as we store a pointer to `n`, instead of `n` in scope

**Comment by danielcdz** [comment]
Hello @TAdev0! I worked on adding that hint, I think I have enough context to solve the issue, so I will be happy to help!

**Comment by TAdev0** [comment]
Hey @danielcdz , someone else is already working on it!
