### ISSUE TITLE
SignedPow

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#441]
Currently, we only implement Pow, not Signed Pow

https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/pow.cairo#L58

**Comment by TAdev0** [comment]
@Sh0g0-1758  are you interested in implementing this hint?

**Comment by Sh0g0-1758** [comment]
Sure thing :)
