### ISSUE TITLE
GetVariableAs methods in Scope

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#448]
Currently in the [scope file](https://github.com/NethermindEth/cairo-vm-go/blob/98ec810b8acc9fdf484b0cf06daf8a323f709f90/pkg/hintrunner/hinter/scope.go#L81), there is a method for getting a variable from the scope directly as a `BigInt` and in [PR#361](https://github.com/NethermindEth/cairo-vm-go/pull/361#discussion_r1630943525) another is being added for `uint64`.
It would be nice to have more functionalities like this for other types, specially for the ones that repeat the most such as Element for handling felts

**Comment by MukulKolpe** [comment]
Hey @cicr99, can I work on this issue?

**Comment by cicr99** [comment]
Sure @MukulKolpe 
Pls notice that for this PR, besides creating the requested functions, you'll also need to modify the places in the code where this logic is used and replace it with the functions you created

**Comment by MukulKolpe** [comment]
Sure @cicr99, thank you for the heads-up. I'll make sure to modify all the parts of the code where this logic is used.

**Comment by TAdev0** [comment]
@MukulKolpe  please wait a bit before working on it so that we can discuss it tomorrow with the team. It seems using generics might be a good idea here as proposed @danielcdz

**Comment by MukulKolpe** [comment]
@TAdev0, Okay, that makes sense. Thanks for informing me. Let me know what the team decides.

**Comment by TAdev0** [comment]
@MukulKolpe  will make a few tests to see whether using generics  decreases efficiency or not , to know if we should them or implementing type by type `getVariableAs` functions

**Comment by danielcdz** [comment]
Great!
