### ISSUE TITLE
feat: create a separate command to run benchmarks

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#526]
Currently, benchmarks are run each time we do `make integration` . This lead to the txt file being overwritten again and again.

**Comment by fmmesen** [comment]
Hello! I'd like to work on this

**Comment by EmmanuelAR** [comment]
Hey @TAdev0 can I work on this?

**Comment by TAdev0** [comment]
Hi ! 
@fmmesen you answered first, i guess i'll assign you.
Can you work on it and propose a PR before the weekend? otherwise you can work on it @EmmanuelAR  so that we can merge this feature before end of week

**Comment by fmmesen** [comment]
Hello @TAdev0 thank you! I'll start it today

**Comment by TAdev0** [comment]
hi @fmmesen  any update?
