### ISSUE TITLE
`DivModNSafeDivPlusOne` hint (ec hint)

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#527]
https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/starknet/security/whitelists/cairo_secp.json#L119

https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/cairo_programs/div_mod_n.cairo#L29

**Comment by danielcdz** [comment]
Hello @TAdev0! I contributed in the past to this project, is this issue available to help you?

**Comment by TAdev0** [comment]
hi @danielcdz  sure go ahead :)

**Comment by danielcdz** [comment]
For sure! thank you @TAdev0

**Comment by danielcdz** [comment]
@TAdev0 I opened this [PR](https://github.com/NethermindEth/cairo-vm-go/pull/551) that solves this issue, I'm open to receive any feedback and any other test cases to include 🫡
