### ISSUE TITLE
`BigIntPackDivmod` + `BigIntSafeDiv` hints (ec hints)

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#530]
whitelisted in ec_bigint.json :

https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/starknet/security/whitelists/ec_bigint.json#L28

https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/cairo_programs/bigint.cairo#L30

https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/cairo_programs/bigint.cairo#L43

**Comment by adrianvrj** [comment]
Hi, can I help with this?

**Comment by TAdev0** [comment]
hi @adrianvrj  sorry for the late answer. Are you still interested in working on this?

This issue includes 2 hints, `BigIntPackDivmod` and `BigIntSafeDiv` hints. They are both required for the integration test here : 
https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/cairo_programs/bigint.cairo

**Comment by adrianvrj** [comment]
> hi @adrianvrj  sorry for the late answer. Are you still interested in working on this?
> 
> 
> 
> This issue includes 2 hints, `BigIntPackDivmod` and `BigIntSafeDiv` hints. They are both required for the integration test here : 
> 
> https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/cairo_programs/bigint.cairo
> 
> 
> 
> 

Hi, sure! I can work on this!

**Comment by TAdev0** [comment]
@adrianvrj  great, feel free to reach out if you encounter any issue

**Comment by adrianvrj** [comment]
Hey @TAdev0 I am trying to reach out via discord :)
