### ISSUE TITLE
`DivModNPackedDivmodExternalN` hint (secp hint)

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#532]
https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/starknet/security/whitelists/cairo_secp.json#L106

https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/vm/src/hint_processor/builtin_hint_processor/hint_code.rs#L618C11-L618C45

**Comment by danielcdz** [comment]
Solving this issue in PR #551

**Comment by danielcdz** [comment]
Hello @TAdev0! As I'm working on this hint, could you assign this issue to me?

**Comment by TAdev0** [comment]
@danielcdz  done, sorry i forgot to assign you
