### ISSUE TITLE
Missing expression in parser

### ISSUE THREAD

**Issue by har777** [NethermindEth/cairo-vm-go#548]
Expressions of the kind `cast(1, felt)` seem to be missing from the parser.

Sample file which can fail: https://github.com/lambdaclass/cairo-vm/blob/main/cairo_programs/bitand_hint.cairo

**Comment by HumbertoTM10** [comment]
Hi @har777 where do you need to add exactly those expressions? In what contexts should these expressions be allowed or expected?

**Comment by cicr99** [comment]
Hey @HumbertoTM10 sorry for the late reply. We found some other expressions apart from the one in this issue that were not supported by our parser, when they should have been. Solving the problem implied a big modification on the hint-reference-parser codebase. PR #625 should be fixing them already
