### ISSUE TITLE
`getHighLen` hint

### ISSUE THREAD

**Issue by TAdev0** [NethermindEth/cairo-vm-go#558]
https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/cairo_programs/highest_bitlen.cairo#L9

https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/starknet/security/whitelists/cairo_secp.json#L17

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-vm-in-go).

### My background and how it can be leveraged
I'm a software developer with experience in backend, I already contributed to cairo vm go in the documentation and now I would like to help in the codebase with this issue.

### How I plan on tackling this issue
I have already read the readme that explains more in depth the requirements, my idea is to analyze the files where I have to add the changes, apply those changes and create the hint implementation and then run the tests to validate that everything is correct.

**Comment by TAdev0** [comment]
hi @coxmars  just assigned you to the issue!
Dont hesitate if you have any question. 

Files to modify (in hintrunner folder) :
- hintcode.go to add the string corresponding to the hint
- zerohint.go to handle the case where we find this string in a cairo zero compiled json file
- corresponding hint file  (probably zerohint_ec.go,  i added it in Math in #164  but its probably more appropriate in elliptic curve hints file)
- zerohint_ec_test.go to add the unit test

Finally, you should copy paste the cairo file here: 
https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/cairo_programs/highest_bitlen.cairo 

in cairo_zero_hint_tests folder for integration tests, to make sure the hint is working normally when used in a cairo program
