### ISSUE TITLE
Build hint map for Cairo 1

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#621]
Currently the `hintrunner` package handles the building of map for the hints for Cairo zero. In the case of Cairo 1, the hints are a lot easier to parse from the compiled output. Let's take this one as an example:
```
[
      834,
      [
        {
          "TestLessThanOrEqual": {
            "lhs": {
              "Immediate": "0x102c"
            },
            "rhs": {
              "Deref": {
                "register": "AP",
                "offset": -12
              }
            },
            "dst": {
              "register": "AP",
              "offset": 0
            }
          }
        }
      ]
    ],
```
Notice they are already named, so there's no need to match the hint against the code string as in previous version. The input parameters for the hint execution already match the hint structures we have implemented for this version (see [TestLessThanOrEquals structure](https://github.com/NethermindEth/cairo-vm-go/blob/ff34f199a27e80ced54c97ad05777de4eb8a8b6e/pkg/hintrunner/core/hint.go#L93) for reference) and the types of the parameters already comply with the current implementation for `operanders`.

Task:
Create a method similar to `GetZeroHints` to produce the `map[uint64][]hinter.Hinter` on account of the program version being used.

> In the main pipeline, it would be a good idea to replace the call to `GetZeroHints` by a general method like `GetHints` (or something like that) that decides, according to the program version, which hint constructor to call

**Comment by danielcdz** [comment]
Hello @cicr99! Hope you are doing well! I can help with this issue if it is possible
