### ISSUE TITLE
Builtin name literals

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#660]
Currently there are several places in the code where the name of a builtin is used as a literal string. For example [here](https://github.com/NethermindEth/cairo-vm-go/blob/4d9322770b8b07cb1a5dba4bef6a0f647bc805ce/pkg/parsers/starknet/starknet.go#L61). Notice that having to write the string each time could cause unwanted typos, and lead to errors in the code.

All the builtin names should be defined as variables (in the `builtin` module most likely), and all the places where the literal strings are used should be replaced with such variables.

**Comment by danielcdz** [comment]
Hey @cicr99 can I help with this one?

**Comment by fishonamos** [comment]
Will love to work on this @cicr99

**Comment by cicr99** [comment]
Sure @danielcdz 🙌 !
Sorry @fishonamos it was requested before you. We'll probably post some new issues in the following days, so keep an eye out. Thanks!

**Comment by danielcdz** [comment]
@cicr99 I opened a PR and left and observation there: https://github.com/NethermindEth/cairo-vm-go/pull/662 👀
